version: '3'
services:
  app:
    build: .
    depends_on:
      - firefox
    hostname: app
    networks:
      - network
  firefox:
    image: selenium/standalone-firefox
    depends_on:
      - tor
    hostname: firefox
    ports:
      - 4444:4444
    networks:
      - network
  tor:
    build:
      dockerfile: Dockerfile.tor
      args:
        - SOCKS_PORT=9100
    hostname: tor
    expose:
      - 9100
    networks:
      - network
networks:
  network:
    driver: bridge
