version: '3'
services:
  app:
    build: .
    depends_on:
      - firefox
    hostname: app
    networks:
      - network
  firefox:
    image: selenium/standalone-firefox
    depends_on:
      - tor
    hostname: firefox
    ports:
      - 4444:4444
      - 7900:7900
    networks:
      - network
  tor:
    build: src/tor
    hostname: tor
    expose:
      - 5000
      - 9100-9109
    networks:
      - network
networks:
  network:
    driver: bridge
