version: '3'
services:
  app:
    build: .
    depends_on:
      - firefox
    hostname: app
    networks:
      - network
  firefox-1:
    image: selenium/standalone-firefox
    depends_on:
      - tor
    hostname: firefox-a
    ports:
      - 4444:4444
      - 7900:7900
    networks:
      - network
  firefox-2:
    image: selenium/standalone-firefox
    depends_on:
      - tor
    hostname: firefox-b
    ports:
      - 4445:4444
      - 7901:7900
    networks:
      - network
  firefox-3:
    image: selenium/standalone-firefox
    depends_on:
      - tor
    hostname: firefox-c
    ports:
      - 4446:4444
      - 7902:7900
    networks:
      - network
  firefox-4:
    image: selenium/standalone-firefox
    depends_on:
      - tor
    hostname: firefox-d
    ports:
      - 4447:4444
      - 7903:7900
    networks:
      - network
  firefox-5:
    image: selenium/standalone-firefox
    depends_on:
      - tor
    hostname: firefox-e
    ports:
      - 4448:4444
      - 7904:7900
    networks:
      - network
  tor:
    build: src/tor
    hostname: tor
    expose:
      - 5000
      - 9100-9109
    networks:
      - network
networks:
  network:
    driver: bridge
